iBlogHub/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using iBlogHub.Areas.Identity.Data;
using iBlogHub.Data;
using iBlogHub.Helpers;
using iBlogHub.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace iBlogHub.Controllers
{
    public class ProfileController : BaseController
    {
        private readonly IPostsService _postService;
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly ICurrentUser _cUser;
        private AppUsers _users;
        public ProfileController(IPostsService postsService,
            ApplicationDbContext context,
            IHostingEnvironment hostingEnvironment,
            ICurrentUser cuser):base(context, postsService)
        {
            _postService = postsService;
            _db = context;
            _hostingEnvironment = hostingEnvironment;
            _cUser = cuser;
        }
        
        [Route("/author/{username}")]
        public async Task<IActionResult> Index(string username="")
        {
            if(username == "")
            {
                return NotFound();
            }
            _users = _db.AppUsers.Where(a => a.UserName == username).Include(a=>a.SocialProfiles).FirstOrDefault();
            var model = await _postService.GetPostsByAuthor(username);
            if (model == null)
            {
                return View(new List<PostsViewModel>());
            }
            ViewData["ProfileUser"] = _users;
            
            return View(model);
        }

        // GET: Profile/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Profile/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profile/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Profile/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Profile/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Profile/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Profile/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: Change Pic
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePic(IFormFile Photo)
        {
            string fileName = "";
            string folderName = "Uploads";
            string webRootPath = _hostingEnvironment.WebRootPath;
            bool success = false;
            string newPath = Path.Combine(webRootPath, folderName);
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }
            if (Photo.Length > 0)
            {
                var filePath = Path.Combine(webRootPath, folderName, Photo.FileName);
                fileName = Photo.FileName;
                using (var stream = System.IO.File.Create(filePath))
                {
                    Photo.CopyTo(stream); 
                }

                var _dbUser = await _db.AppUsers.Where(a => a.Id == _cUser.User.Id).FirstOrDefaultAsync();
                _dbUser.Photo = fileName;
                _dbUser.PhotoPath = "Uploads";
                await _db.SaveChangesAsync();
                success = true;
            }
            return Json(new { error = success, msg = "Your Profile has been updated." });
        }
    }
}

iBlogHub/Controllers/StoriesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using iBlogHub.Data;
using iBlogHub.Helpers;
using iBlogHub.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using PagedList.Core;
using static iBlogHub.Helpers.Enums;

namespace iBlogHub.Controllers
{

    public class StoriesController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IPostsService _postsService;
        private readonly ICurrentUser _user;
        private readonly ILogger<PostsInputModel> _logger;
        private readonly IHostingEnvironment _hostingEnvironment;

        public StoriesController(ApplicationDbContext context,
            IPostsService postsService,
             ILogger<PostsInputModel> logger,
            ICurrentUser user, IHostingEnvironment hostingEnvironment) : base(context, postsService)
        {
            _context = context;
            _postsService = postsService;
            _user = user;
            _logger = logger;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            var model = await _postsService.Get();
            
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Post()
        {
            return View("_NewPost", new PostInputCategoryModel());            
        }

        [HttpPost]
        public IActionResult Post(PostInputCategoryModel model)
        {
            if (!string.IsNullOrEmpty(model.Category))
            {
                var _quotesCheck = _context.Categories.Where(a => a.Id.ToString() == model.Category).FirstOrDefault();
                if (_quotesCheck.Title.Equals("Quotation"))
                {
                    return View("QuotesCreate", new PostsInputModel { isCategorySelected = true, Category = model.Category });
                }
                else
                {
                    return View("Create", new PostsInputModel { isCategorySelected = true, Category = model.Category, SelectedCategoryName = _quotesCheck.Title });
                }                
            }
            else
            {
                return View("_NewPost", new PostInputCategoryModel());
            }
        }

        [Authorize]
        public async Task<IActionResult> Edit(string slug = "")
        {
            if (slug == "")
            {
                return Error();
            }
            var posts = await _postsService.Get(slug);
           
            if (posts == null)
            {
                ErrorViewModel error = new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    ErrorType = ErrorType.Posts
                };
                return View("Error", error);
            }

            if (_user.User.Id != posts.Author.Id)
            {
                return View("Notauthorized");
            }

            var _ptags = await _postsService.GetPostTags(posts.Id);
            IList<string> Ktags = new List<string>();
            string tags = "";
            foreach (var item in _ptags)
            {
                Ktags.Add(item.Name);
            }
            tags = string.Join(",", Ktags);
            PostsInputModel model = new PostsInputModel
            {
                id = posts.Id,
                Category = GetPostCategory(posts),
                CommentStatus = posts.CommentStatus == CommentStatus.Allowed ? true : false,
                Description = posts.PostContent,
                Excerpt = posts.Excerpt,
                PostFeaturedImage = posts.FeaturedImage,
                Tags = tags,
                Title = posts.PostTitle
            };
            
            var _quotesCheck = _context.Categories.Where(a => a.Id.ToString() == model.Category).FirstOrDefault();
            var _selCategories = _postsService.Categories;
            var CategorySelectList = new List<SelectListItem>();
            foreach (var item in _selCategories)
            {
                CategorySelectList.Add(new SelectListItem
                {
                    Text = item.Name,
                    Selected = (item.Id == _quotesCheck.Id) ? true : false,
                    Value = item.Id.ToString()
                });
            }
            ViewData["CategorySelectList"] = CategorySelectList;
            if (_quotesCheck.Title.Equals("Quotation"))
            {
                return View("QuotesEdit", model);
            }

            
            return View("Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, PostsInputModel model)
        {
            
            var _quotesCheck = _context.Categories.Where(a => a.Id.ToString() == model.Category).FirstOrDefault();
            if (_quotesCheck.Title.Equals("Quotation"))
            {
                if (!string.IsNullOrEmpty(model.Description))
                {
                    var content = Html2PlainText.Decode(model.Description);
                    model.Title = content.Length > 100 ? content.Substring(0, 99) : content;
                    model.Excerpt = content.Length > 255 ? content.Substring(0, 254) : content; //.Substring(0, 255);
                }
                else
                {
                    //ModelState.AddModelError("", "Please provide a valid content");
                    return View("QuotesCreate", model);
                }
            }
            if (!ModelState.IsValid)
            {
                if (_quotesCheck.Title.Equals("Quotation"))
                {
                    ModelState.AddModelError("", "Some error occurred. Please try again later.");
                    return View("QuotesEdit", model);
                }
                else
                {
                    return View("Edit", model);
                }
                
            }
            ResultsModel result = await _postsService.Edit(id, model);
            if (result.Success)
            {
                return RedirectToAction("Success", new { slug = result.Slug, edit = 1, category = _quotesCheck.Title });
            }
            else
            {
                if (_quotesCheck.Title.Equals("Quotation"))
                {
                    return View("QuotesEdit", model);
                }
                else
                {
                    return View("Edit", model);
                }
               
            }
           
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return RedirectToAction(nameof(Post));
        }

        [HttpPost]
        public async Task<IActionResult> Create(PostsInputModel model)
        {
            var _quotesCheck = _context.Categories.Where(a => a.Id.ToString() == model.Category).FirstOrDefault();
            if (_quotesCheck.Title.Equals("Quotation"))
            {
                if (!string.IsNullOrEmpty(model.Description))
                {
                    var content = Html2PlainText.Decode(model.Description);
                    model.Title = content.Length > 100 ? content.Substring(0, 99) : content;
                    model.Excerpt = content.Length > 255 ? content.Substring(0, 254) : content;                    
                }
                else
                {
                    return View("QuotesCreate", model);
                }
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    if (_quotesCheck.Title.Equals("Quotation"))
                    {
                        ModelState.AddModelError("", "Some error occurred. Please try again later.");
                        return View("QuotesCreate", model);
                    }
                    else
                    {
                        return View("Create", model);
                    }
                }
            }
           
            ResultsModel result = await _postsService.Create(model);
            if (result.Success)
            {
                return RedirectToAction("Success", new { slug = result.Slug, edit = 0, category = _quotesCheck.Title });
            }
            else
            {
                if (_quotesCheck.Title.Equals("Quotation"))
                { 
                    return View("QuotesCreate", model); 
                }
                else
                {
                    return View("Create", model);
                }                    
            }
        }

        [Authorize]
        public IActionResult Success(string slug, int? edit = 0, string category = "")
        {
            
            var Posts = _context.Posts.Where(a => a.slug.Equals(slug)).Select(a => new PostsViewModel
            {
                Id = a.Id,
                PostTitle = a.PostTitle,
                slug = a.slug,
                Status = a.Status,
                ViewCategory = category
            }).FirstOrDefault();

            if (edit == 1)
                Posts.Message = "Your Post was modified successfully.";
            else
                Posts.Message = "Your Post has been published and is pending review, you'll see it live within few minutes. Thanks!";

            if (Posts == null)
            {

iBlogHub/Views/Stories/Featured.cshtml
@model IEnumerable<iBlogHub.Models.PostsViewModel>
@{
    ViewData["Title"] = "Featured Posts on iBlogHub";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Categories = _postsService.Categories;
    ViewBag.IncludeAds = true;
    ViewBag.KeyWords = "Collection,Stories,Codes,and,Latest,Articles, ibloghub, blogs, " +
                "blog, posts, categories, featured posts on ibloghub";
    ViewBag.MetaDescription = "Recent Stories, Articles and Learning contents";
    List<Guid> usedIds = new List<Guid>();
}

@section Seo{

    @if (_postsService.FeaturedPosts.Count() > 0)
    {
        <meta name="image" content="~/Uploads/@_postsService.FeaturedPosts.Where(a => a.FeaturedImage != null).FirstOrDefault().FeaturedImage" />
    }
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 main-loop">
            @*<h4 class="font-weight-bold spanborder">
                <span>Featured Posts</span>
            </h4>*@
            @if (_postsService.FeaturedPosts.Count() >= 1)
            {
                foreach (var item in _postsService.FeaturedPosts.Where(a => !string.IsNullOrEmpty(a.FeaturedImage)).OrderBy(a => a.Id).Take(1))
                {
                    await Html.RenderPartialAsync("_PostSingleFeatured", item);
                    usedIds.Add(item.Id);
                }
                <div class="spanborder"></div>
                await Html.RenderPartialAsync("_MainPostsWidget", _postsService.FeaturedPosts.Where(a => !usedIds.Contains(a.Id)).Take(16));

            }

            @if (_postsService.FeaturedPosts.Count() > 10)
            {
                <div class="mt-5">
                    <ul class="pagination">
                        @for (var i = 1; i <= _postsService.FeaturedPosts.Count(); i++)
                        {
                            <li class="page-item @(i == _postsService.FeaturedPosts.Count() ? "active" : "")">
                                <a asp-controller="Stories" asp-action="Index" asp-route-currentpage="@i" class="page-link">@i</a>
                            </li>
                        }
                    </ul>
                    @*@PagedList.Core.PagedListPager(_postsService.FeaturedPosts, page => Url.Action("Index", new { page = page }),
                        new PagedListRenderOptions
                        {
                            UlElementClasses = new string[] { "pagination" },
                            LiElementClasses = new string[] { "page-item" },
                            DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                            DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
                            LinkToPreviousPageFormat = string.Format("« Prev"),
                            LinkToLastPageFormat = string.Format("»"),

                        })*@

                </div>
            }

            <div class="clearfix"></div>
            <div class="featured-category text-right mt-3 pb-3 text-uppercase smaller">
                <a href="@Url.Action("Index", "Stories")">
                    All Stories <i class="fa fa-angle-right"></i>
                </a>

                <div class="clearfix"></div>
            </div>


            <div class="clearfix"></div>


        </div>

        <div class="col-md-4">
            <div class="sticky-top sticky-top-offset">
                <div class="col-sm-12">
                    <div id="allcategories" class="display-categories">
                        <h6 class="font-weight-bold spanborder">
                            <span>TOP CATEGORIES</span>
                        </h6>

                        @if (Categories.Count > 0)
                        {
                            <div class="row">
                                <div class="col-sm-12">
                                    @foreach (var item in Categories.Where(a => a.Posts.Count != 0).Take(5)) //.Where(a => a.Articles.Count > 5)
                                    {

                                        <a href="@Url.Action("Posts", "Categories", new { slug = item.slug})">
                                            <h5 style="cursor:pointer;" class="font-weight-bold ">
                                                <span>
                                                    @item.Name <span class="text-primary text-muted text-sm-left" style="font-weight:lighter">@item.Posts.Count Posts</span>
                                                </span>
                                            </h5>
                                        </a>
                                        <hr />

                                    }
                                </div>
                            </div>
                            <div class="featured-category text-right mt-3 pb-3 text-uppercase smaller">
                                <a href="@Url.Action("Index", "Categories")">
                                    All Categories <i class="fa fa-angle-right"></i>
                                </a>

                                <div class="clearfix"></div>
                            </div>

                        }
                        <partial name="_sidebarAds" />

                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>


@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script src="~/lib/highlight/prism.js"></script>
    <script src="~/js/notify.js"></script>
    <script src="~/js/prettify.js"></script>
    <script type="text/javascript">

        var onBegin = function () {
            $("#loader").fadeIn();
        };
        function Notify(data) {
            $("#loader").fadeOut();

            if (data.error == true) {
                Swal.fire({
                    icon: "success",
                    html: data.msg,
                    showConfirmButton: false,
                    timer: 1500
                })
            }
            else {
                Swal.fire({
                    icon: "success",
                    html: data.msg,
                    showConfirmButton: false,
                    timer: 1500
                })
            }

        }
        function NotifyError(data) {
            $("#loader").fadeOut();
            Swal.fire({
                title: "Error!",
                text: "Some error occurred, please try again later.",
                buttonsStyling: true
            });

        }
    </script>

}

iBlogHub/Views/Stories/Index.cshtml
@using PagedList;
@using PagedList.Core;
@model IEnumerable<iBlogHub.Models.PostsViewModel>
@{
    ViewBag.Title = "Read Stories, Articles and inspirational contents";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Featured = _postsService.FeaturedPosts;
    var Categories = _postsService.Categories;
    ViewBag.IncludeAds = true;
    ViewBag.KeyWords = "Collection,Stories,Codes,and,Latest,Articles, ibloghub, blogs, blog, posts";
    ViewBag.MetaDescription = "Recent Stories, Articles and Learning contents";
    List<Guid> usedIds = new List<Guid>();
}
@section Seo{

    @if (Model.Count() > 0)
    {
        <meta name="image" content="~/Uploads/@Model.Where(a => a.FeaturedImage != null).FirstOrDefault().FeaturedImage" />
    }
}

<div class="container">
    <div class="page-content">
        <div class="row mt-3">
            <div class="col-md-8 main-loop col-sm-12">                
                @if (Model.Count() >= 1 || Model != null)
                {
                    foreach (var item in Model.Where(a => !string.IsNullOrEmpty(a.FeaturedImage)).OrderBy(a => a.Id).Take(1))
                    {
                        await Html.RenderPartialAsync("_PostSingleFeatured", item);
                        usedIds.Add(item.Id);
                    }
                    <div class="clearfix"></div>
                    <p class="spanborder small">@*<span>Latest</span>*@</p>
                    await Html.RenderPartialAsync("_MainPostsWidget", Model.Where(a => !usedIds.Contains(a.Id)).Take(16));
                }



                @*@if (Model.Count() > 10)
        {
            <div class="mt-5">
                <ul class="pagination">
                    @for (var i = 1; i <= Model.Count(); i++)
                    {
                        <li class="page-item @(i == Model.Count() ? "active" : "")">
                            <a asp-controller="Stories" asp-action="Index" asp-route-currentpage="@i" class="page-link">@i</a>
                        </li>
                    }
                </ul>
                @PagedList.Core.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
        new PagedListRenderOptions
        {
            UlElementClasses = new string[] { "pagination" },
            LiElementClasses = new string[] { "page-item" },
            DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
            DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
            LinkToPreviousPageFormat = string.Format("« Prev"),
            LinkToLastPageFormat = string.Format("»"),

        })

            </div>
                } *@

                <div class="clearfix"></div>

                <div class="spanborder"></div>
                @{
                    await Html.RenderPartialAsync("_CategoryWidget", Categories);

                }
            </div>

            <div class="col-md-4">
                <div class="sticky-top sticky-top-offset">
                    <div class="col-sm-12">
                        @{
                            await Html.RenderPartialAsync("_featuredPosts", Featured);
                        }
                        <partial name="_sidebarAds" />
                    </div>
                </div>
              
            </div>
        </div>
    </div>
</div>

iBlogHub/Views/Stories/Quotes.cshtml
@using PagedList;
@using PagedList.Core;
@model IEnumerable<iBlogHub.Models.PostsViewModel>
@{
    ViewBag.Title = "Quotes";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Featured = _postsService.FeaturedPosts;
    var Categories = _postsService.Categories;
    ViewBag.IncludeAds = true;
    ViewBag.KeyWords = "Collection,Stories,Codes,and,Latest,Articles, ibloghub, blogs, blog, posts, quotes, quotes of the day";
    ViewBag.MetaDescription = "Quotes";
    List<Guid> usedIds = new List<Guid>();

}
@section Seo{

    @if (Model.Count() > 0)
    {
        <meta name="image" content="~/Uploads/@Model.Where(a => a.FeaturedImage != null).FirstOrDefault().FeaturedImage" />
    }
}
@*<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-6t+ed+2i-1n-4w"
     data-ad-client="ca-pub-0986464081027217"
     data-ad-slot="2247884424"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>*@
<div class="container">
    <div class="page-content">
        <div class="form-group row  mt-3">
            <div class="col-sm-12 col-md-8 col-lg-8">

                <div class="form-group row">
                    <div class="card-columns">
                        @foreach (var item in Model)
                        {

                            <div class="">
                                @*col-sm-6 mb-4 mb-md-0 col-md-6 pb-5*@
                                <div class="card border cardwithshadow onhoverup">
                                    @if (!string.IsNullOrEmpty(item.FeaturedImage))
                                    {
                                        <div class="pr-0 align-self-center">
                                            <a href="@Url.Action("Index", "Posts", new { category= item.Category.slug, slug = item.slug})">
                                                <img class="rounded w-100" style="max-height:250px;" src="~/Uploads/@item.FeaturedImage" alt="@item.PostContent">
                                            </a>
                                        </div>
                                    }

                                    <div class="pr-0 pr-md-4 pt-4 pb-4">
                                        <div class="col-sm-12">

                                            <h6 class="card-title">
                                                <a class="" style="color:#1b1b1b" href="@Url.Action("Index", "Posts", new { category= item.Category.slug, slug = item.slug})">

                                                    @Html.Raw(item.PostContent)

                                                </a>

                                            </h6>


                                            <div>
                                                @{
                                                    await Html.RenderPartialAsync("_PostFooterSection", item);
                                                }
                                            </div>
                                        </div>

                                    </div>

                                </div>

                            </div>

                        }
                    </div>

                </div>

            </div>
            <div class="col-md-4">
                <div class="sticky-top sticky-top-offset">
                    <div class="col-sm-12">
                        <div class="col-sm-12">
                            <p>
                                <b class="font-weight-bold h5">Quotes</b>
                            </p>
                            <a class="btn btn-outline-success btn-sm btn-default" href="#follow-Category">Follow</a>
                            <div class="mt-3">
                                <p>
                                    <small class="text-muted">
                                        Last post on @Model.OrderByDescending(a => a.PostDate).Take(1).FirstOrDefault().PostDate.ToString("dd MMM, yyyy")
                                        by
                                        <a class="text-muted" href="@Url.Action("Index", "Profile", new { username = Model.OrderByDescending(a => a.PostDate).Take(1).FirstOrDefault().Author.UserName })">
                                            @Model.OrderByDescending(a => a.PostDate).Take(1).FirstOrDefault().Author.FirstName
                                        </a>

                                    </small>
                                </p>
                            </div>
                            <p>&nbsp;</p>
                            @*<div class="spanborder"></div>*@
                        </div>

                    </div>
                    <div class="col-sm-12">
                        @{
                            await Html.RenderPartialAsync("_featuredPosts", Featured);
                        }
                        <partial name="_sidebarAds" />
                    </div>
                </div>

            </div>

        </div>

    </div>
</div>

iBlogHub/Views/Stories/Success.cshtml
@model iBlogHub.Models.PostsViewModel
@{
    ViewData["Title"] = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles{
    <style type="text/css">
        .center {
            margin: auto;
            padding: 70px 0;
        }
    </style>
}
<div class="container">
    <div class="page-content" id="wrapper">
        <div class="row d-flex h-100">
            <div class="col-sm-12">
                <div class="center">
                    <div class="">
                        <h2>@Model.PostTitle</h2>
                        @if (Model.HasMessage)
                        {
                            <p class="text-muted">
                                @Model.Message Click <a href="@Href($"~/{Model.ViewCategory}/{Model.slug}")">here</a> to preview.
                            </p>
                        }
                        <p class="text-muted">To edit your post again, click <a href="@Url.Action("Edit", "Stories", new { slug = Model.slug})">here</a>.</p>
                        <p>
                            Meanwhile,<br />
                            <a href="@Href("~/Identity/Account/Manage/MyStories")" class="btn btn-default"><i class="fa fa-th-list"></i> Check all your Stories</a><br />
                            <a class="btn btn-default" href="@Href("~/Identity/Account/Manage/")">
                                <i class="fa fa-user"></i> Visit your Profile
                            </a>   <br />
                            <a href="@Url.Action("Index", "Home")" class="btn btn-default"><i class="fa fa-home"></i> Back to Home Page</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>